import type { ReviewResult, Finding, Severity } from "../types.js";
import { countBySeverity } from "../pipeline/aggregator.js";
import * as fs from "node:fs";
import * as path from "node:path";

/** Generate a markdown review report */
export function generateReport(result: ReviewResult): string {
  const counts = countBySeverity(result.findings);
  const lines: string[] = [];

  lines.push(`# PR Review: #${result.pr.number} — ${result.pr.title}`);
  lines.push("");
  lines.push(`**Reviewed**: ${result.reviewedAt}`);
  lines.push(`**Author**: ${result.pr.author}`);
  lines.push(`**Branch**: ${result.pr.headBranch} → ${result.pr.baseBranch}`);
  lines.push(`**Decision**: ${result.verdict}`);
  lines.push(`**Actionable Rate**: ${Math.round(result.actionableRate * 100)}%`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(result.summary || "No summary generated.");
  lines.push("");// File table
  lines.push("## Changes Analyzed");
  lines.push("");
  lines.push("| File | Changes | Status |");
  lines.push("|------|---------|--------|");
  for (const file of result.pr.files.slice(0, 30)) {
    lines.push(
      `| ${file.filename} | +${file.additions} -${file.deletions} | ${file.status} |`
    );
  }
  if (result.pr.files.length > 30) {
    lines.push(`| ... | ${result.pr.files.length - 30} more files | |`);
  }
  lines.push("");

  // Findings by severity
  const severities: Severity[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW"];
  for (const severity of severities) {
    const group = result.findings.filter((f) => f.severity === severity);
    if (group.length === 0) {
      lines.push(`## ${severity} (0)`);
      lines.push("");
      lines.push("None.");
      lines.push("");
      continue;
    }

    lines.push(`## ${severity} (${group.length})`);
    lines.push("");

    for (const f of group) {
      lines.push(`### [${severity}] ${f.issue}`);
      lines.push("");
      lines.push(`- **File**: \`${f.file}${f.line ? ":" + f.line : ""}\``);
      lines.push(`- **Dimension**: ${f.dimension}`);
      lines.push(`- **Category**: ${f.category}`);
      if (f.fix && f.fix !== "See issue description") {
        lines.push(`- **Fix**: ${f.fix}`);
      }lines.push("");
    }
  }

  // Dimensions coverage
  lines.push("## Review Dimensions");
  lines.push("");
  lines.push("| Dimension | Findings |");
  lines.push("|-----------|----------|");
  for (const dim of result.dimensionsRun) {
    const count = result.findings.filter((f) => f.dimension === dim).length;
    lines.push(`| ${dim} | ${count} |`);
  }
  lines.push("");

  lines.push("---");
  lines.push(
    `*Report generated by [pr-review-assistant](https://github.com) on ${result.reviewedAt}*`
  );
  lines.push("");

  return lines.join("\n");
}

/** Save the report to disk */
export function saveReport(result: ReviewResult): string {
  const dir = ".pr-review";
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const filename = `pr-${result.pr.number}-review.md`;
  const filepath = path.join(dir, filename);
  const content = generateReport(result);
  fs.writeFileSync(filepath, content, "utf-8");
  return filepath;
}

/** Generate just the summary section (for GitHub review body) */
export function generateGitHubBody(result: ReviewResult): string {
  const counts = countBySeverity(result.findings);
  const parts: string[] = [];

  parts.push(`## AI Review Summary`);
  parts.push("");
  parts.push(result.summary || "Automated review completed.");
  parts.push("");


  if (result.findings.length === 0) {
    parts.push(":white_check_mark: No issues found.");
  } else {
    parts.push(
      `:mag: **${result.findings.length} finding(s)** | ${counts.CRITICAL} critical, ${counts.HIGH} high, ${counts.MEDIUM} medium, ${counts.LOW} low`
    );
    parts.push(`:bar_chart: Actionable rate: ${Math.round(result.actionableRate * 100)}%`);
    parts.push(`:scales: Verdict: **${result.verdict}**`);
  }

  parts.push("");
  parts.push("---");
  parts.push(
    `:robot: *Automated review by [pr-review-assistant]* | ${result.reviewedAt}`
  );

  return parts.join("\n");
}

/** Generate inline review comments for GitHub */
export function generateInlineComments(
  findings: Finding[]
): Array<{ path: string; line: number; body: string }> {
  const comments: Array<{ path: string; line: number; body: string }> = [];

  for (const f of findings) {
    if (f.line && f.file) {
      const sev = f.severity === "CRITICAL" ? "🔴" : f.severity === "HIGH" ? "🟡" : "🔵";comments.push({
        path: f.file,
        line: f.line,
        body: `${sev} **${f.severity}** (${f.dimension}): ${f.issue}\n\nSuggested fix: ${f.fix}`,
      });
    }
  }

  return comments;
}

/**
 * Submit the review as a GitHub PR review via the API.
 * Posts both a summary body and inline line comments.
 */
export async function submitGitHubReview(
  result: ReviewResult,
  token: string
): Promise<{ ok: boolean; status: number; message: string }> {
  const { owner, repo, number } = result.pr;
  const body = generateGitHubBody(result);
  const comments = generateInlineComments(result.findings);

  const resp = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${number}/reviews`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
        "User-Agent": "pr-review-assistant",
      },
      body: JSON.stringify({
        event: "COMMENT",
        body,
        comments: comments.map((c) => ({
          path: c.path,
          line: c.line,
          body: c.body,
        })),
      }),
    }
  );

  const text = await resp.text();
  return {
    ok: resp.ok,
    status: resp.status,
    message: text.slice(0, 500),
  };
}