import type { ReviewResult, Finding, Severity } from "../types.js";
import { countBySeverity, SEVERITY_ORDER } from "../pipeline/aggregator.js";
import * as fs from "node:fs";
import * as path from "node:path";

/** Generate a markdown review report */
export function generateReport(result: ReviewResult): string {
  const counts = countBySeverity(result.findings);
  const lines: string[] = [];

  lines.push(`# PR Review: #${result.pr.number} — ${result.pr.title}`);
  lines.push("");
  lines.push(`**Reviewed**: ${result.reviewedAt}`);
  lines.push(`**Author**: ${result.pr.author}`);
  lines.push(`**Branch**: ${result.pr.headBranch} → ${result.pr.baseBranch}`);
  lines.push(`**Decision**: ${result.verdict}`);
  lines.push(`**Actionable Rate**: ${Math.round(result.actionableRate * 100)}%`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(result.summary || "No summary generated.");
  lines.push("");

  if (result.zhSummary) {
    lines.push("### 中文摘要");
    lines.push("");
    lines.push(result.zhSummary);
    lines.push("");
  }

  // File table
  lines.push("## Changes Analyzed");
  lines.push("");
  lines.push("| File | Changes | Status |");
  lines.push("|------|---------|--------|");
  for (const file of result.pr.files.slice(0, 30)) {
    lines.push(
      `| ${file.filename} | +${file.additions} -${file.deletions} | ${file.status} |`
    );
  }
  if (result.pr.files.length > 30) {
    lines.push(`| ... | ${result.pr.files.length - 30} more files | |`);
  }
  lines.push("");

  // Findings by severity
  const severities: Severity[] = [...SEVERITY_ORDER];
  for (const severity of severities) {
    const group = result.findings.filter((f) => f.severity === severity);
    if (group.length === 0) {
      lines.push(`## ${severity} (0)`);
      lines.push("");
      lines.push("None.");
      lines.push("");
      continue;
    }

    lines.push(`## ${severity} (${group.length})`);
    lines.push("");

    for (const f of group) {
      lines.push(`### [${severity}] ${f.verdict === "CONFIRMED" ? "✅已确认" : "⚠️存疑"} — ${f.issue}`);
      lines.push("");
      lines.push(`- **File**: \`${f.file}${f.line ? ":" + f.line : ""}\``);
      lines.push(`- **Dimension**: ${f.dimension}`);
      lines.push(`- **Category**: ${f.category}`);
      if (f.fix && f.fix !== "See issue description") {
        lines.push(`- **Fix**: ${f.fix}`);
      }
      if (f.zhBrief) {
        lines.push("");
        lines.push(`> ${f.zhBrief}`);
      }
      lines.push("");
    }
  }

  // Per-file finding summary
  lines.push("## Findings by File");
  lines.push("");
  lines.push("| File | CRITICAL | HIGH | MEDIUM | LOW | Total |");
  lines.push("|------|----------|------|--------|-----|-------|");

  const byFile = new Map<string, Record<Severity, number>>();
  for (const f of result.findings) {
    const file = f.file || "(unknown)";
    if (!byFile.has(file)) {
      byFile.set(file, { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 });
    }
    byFile.get(file)![f.severity]++;
  }

  const sortedFiles = [...byFile.entries()].sort((a, b) => {
    const totalA = Object.values(a[1]).reduce((s, c) => s + c, 0);
    const totalB = Object.values(b[1]).reduce((s, c) => s + c, 0);
    if (totalA !== totalB) return totalB - totalA;
    return a[0].localeCompare(b[0]);
  });

  for (const [file, counts] of sortedFiles) {
    const total = Object.values(counts).reduce((s, c) => s + c, 0);
    lines.push(`| ${file} | ${counts.CRITICAL || "-"} | ${counts.HIGH || "-"} | ${counts.MEDIUM || "-"} | ${counts.LOW || "-"} | ${total} |`);
  }
  lines.push("");

  // Dimensions coverage
  lines.push("## Review Dimensions");
  lines.push("");
  lines.push("| Dimension | Findings |");
  lines.push("|-----------|----------|");
  for (const dim of result.dimensionsRun) {
    const count = result.findings.filter((f) => f.dimension.split(", ").includes(dim)).length;
    lines.push(`| ${dim} | ${count} |`);
  }
  lines.push("");

  lines.push("---");
  lines.push(
    `*Report generated by [pr-review-assistant](https://github.com) on ${result.reviewedAt}*`
  );
  lines.push("");

  return lines.join("\n");
}

/** Save the report to disk */
export function saveReport(result: ReviewResult): string {
  const dir = ".pr-review";
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const filename = `pr-${result.pr.number}-review.md`;
  const filepath = path.join(dir, filename);
  const content = generateReport(result);
  fs.writeFileSync(filepath, content, "utf-8");
  return filepath;
}

/** Generate just the summary section (for GitHub review body) */
export function generateGitHubBody(result: ReviewResult): string {
  const counts = countBySeverity(result.findings);
  const parts: string[] = [];

  parts.push(`## AI Review Summary`);
  parts.push("");
  parts.push(result.summary || "Automated review completed.");
  parts.push("");

  if (result.zhSummary) {
    parts.push("");
    parts.push("**中文摘要**: " + result.zhSummary);
  }

  if (result.findings.length === 0) {
    parts.push(":white_check_mark: No issues found.");
  } else {
    const confirmedCount = result.findings.filter((f) => f.verdict === "CONFIRMED").length;
    const plausibleCount = result.findings.length - confirmedCount;
    parts.push(
      `:mag: **${result.findings.length} finding(s)** | ${counts.CRITICAL} critical, ${counts.HIGH} high, ${counts.MEDIUM} medium, ${counts.LOW} low`
    );
    parts.push(`:white_check_mark: 已确认: ${confirmedCount} | :warning: 存疑: ${plausibleCount}`);
    parts.push(`:bar_chart: Actionable rate: ${Math.round(result.actionableRate * 100)}%`);
    parts.push(`:scales: Verdict: **${result.verdict}**`);
  }

  parts.push("");
  parts.push("---");
  parts.push(
    `:robot: *Automated review by [pr-review-assistant]* | ${result.reviewedAt}`
  );

  return parts.join("\n");
}

/** Generate inline review comments for GitHub */
export function generateInlineComments(
  findings: Finding[]
): Array<{ path: string; line: number; body: string }> {
  const comments: Array<{ path: string; line: number; body: string }> = [];

  for (const f of findings) {
    if (f.line != null && f.file) {
      const sev = f.severity === "CRITICAL" ? "🔴" : f.severity === "HIGH" ? "🟡" : "🔵";
      const verdictLabel = f.verdict === "CONFIRMED" ? "已确认" : "存疑";
      const zhLine = f.zhBrief ? `\n\n简评: ${f.zhBrief}` : "";
      comments.push({
        path: f.file,
        line: f.line,
        body: `${sev} **${f.severity}** [${verdictLabel}] (${f.dimension}): ${f.issue}${zhLine}\n\nSuggested fix: ${f.fix}`,
      });
    }
  }

  return comments;
}

/** Map internal verdict to GitHub review event */
function verdictToGitHubEvent(verdict: string): string {
  if (verdict === "BLOCK" || verdict === "REQUEST_CHANGES") return "REQUEST_CHANGES";
  return "COMMENT";
}

/**
 * Submit the review as a GitHub PR review via the API.
 * Posts both a summary body and inline line comments.
 */
export async function submitGitHubReview(
  result: ReviewResult,
  token: string
): Promise<{ ok: boolean; status: number; message: string }> {
  const { owner, repo, number } = result.pr;
  const body = generateGitHubBody(result);
  const comments = generateInlineComments(result.findings);

  const resp = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${number}/reviews`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
        "User-Agent": "pr-review-assistant",
      },
      body: JSON.stringify({
        event: verdictToGitHubEvent(result.verdict),
        commit_id: result.pr.headSha,
        body,
        comments: comments.map((c) => ({
          path: c.path,
          line: c.line,
          body: c.body,
        })),
      }),
    }
  );

  const text = await resp.text();
  return {
    ok: resp.ok,
    status: resp.status,
    message: text.slice(0, 500),
  };
}
