/** Severity levels for review findings */
export type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";

/** Review dimensions — extensible via registerDimension() */
export type Dimension = string;

/** File change status in a PR */
export type FileStatus = "added" | "modified" | "renamed" | "removed" | "changed";

/** A single file from a PR */
export interface PRFile {
  filename: string;
  status: FileStatus;
  additions: number;
  deletions: number;
  changes: number;
  patch?: string;
  blob_url?: string;
  raw_url?: string;
  contents_url?: string;
}

/** PR metadata from GitHub */
export interface PRMetadata {
  owner: string;
  repo: string;
  number: number;
  title: string;
  body: string | null;
  author: string;
  baseBranch: string;
  headBranch: string;
  state: "open" | "closed" | "merged";
  draft: boolean;
  mergeable: string | null;
  files: PRFile[];
  additions: number;
  deletions: number;
  changedFiles: number;
  commits: PRCommit[];
  ciStatus: CICheck[];
  headSha?: string;
}

/** A commit on the PR branch */
export interface PRCommit {
  sha: string;
  message: string;
  author: string;
  date: string;
}

/** CI check status */
export interface CICheck {
  name: string;
  status: string;
  conclusion: string | null;
}

/** A single review finding */
export interface Finding {
  severity: Severity;
  dimension: Dimension;
  file: string;
  line?: number;
  endLine?: number;
  category: string;
  issue: string;
  fix: string;
  confidence: number;
  /** Chinese one-line brief assessment (generated by LLM) */
  zhBrief?: string;
  /** Exact code line(s) from the diff that triggered this finding (used for grounding verification) */
  codeQuote?: string;
  /** LLM verification verdict — CONFIRMED / PLAUSIBLE / REFUTED */
  verdict?: "CONFIRMED" | "PLAUSIBLE" | "REFUTED";
}

/** Aggregated review result */
export interface ReviewResult {
  pr: PRMetadata;
  findings: Finding[];
  summary: string;
  /** Chinese summary paragraph (generated by LLM) */
  zhSummary?: string;
  verdict: "BLOCK" | "REQUEST_CHANGES" | "COMMENT";
  actionableRate: number;
  reviewedAt: string;
  dimensionsRun: Dimension[];
}

/** Progress event emitted during review */
export interface ReviewProgress {
  phase: "fetch" | "filter" | "review" | "aggregate" | "report" | "done" | "error";
  message: string;
  detail?: string;
  percent?: number;
  /** Estimated seconds remaining (present when percent > 0) */
  etaSeconds?: number;
  /** Per-dimension status map */
  dimensionStatus?: Record<string, "pending" | "running" | "done" | "failed">;
}

/** Configuration options */
export interface ReviewConfig {
  prIdentifier: string;
  deep: boolean;
  output: "terminal" | "markdown" | "github" | "all";
  dimensions: Dimension[];
  maxFiles: number;
  /** Glob patterns for files to exclude from review (in addition to built-in patterns) */
  exclude?: string[];
  verbose: boolean;
  onProgress?: (event: ReviewProgress) => void;
  provider?: ProviderType;
  apiKey?: string;
  apiBaseUrl?: string;
  modelOverride?: string;
  /** Model for the review/finding phase (defaults to modelOverride or provider default) */
  reviewModel?: string;
  /** Model for the verify/summarize phase (defaults to modelOverride or provider default) */
  verifyModel?: string;
  githubToken?: string;
}

import type { ProviderType } from "./models/provider-registry.js";
export type { ProviderType };

/** Provider configuration */
export interface ProviderConfig {
  type: ProviderType;
  apiKey: string;
  baseUrl?: string;
  model: string;
}

/** Stored credentials (for Web UI settings) */
export interface StoredSettings {
  provider: ProviderType;
  keys: Record<string, string>;
  baseUrls: Record<string, string>;
  models: Record<string, string>;
  githubToken: string;
  reviewModel: string;
  verifyModel: string;
}

/** Feedback label for a finding */
export type FeedbackLabel = "fp" | "fn" | "tp";

/** User feedback on a finding */
export interface FindingFeedback {
  file: string;
  category: string;
  label: FeedbackLabel;
  timestamp: string;
}

/** Feedback store persisted to disk */
export interface FeedbackStore {
  entries: FindingFeedback[];
  falsePositivePatterns: Array<{ filePattern: string; category: string }>;
}

/** Context bundle passed to each dimension reviewer */
export interface ReviewContext {
  pr: PRMetadata;
  filteredFiles: PRFile[];
  highRiskFiles: PRFile[];
  fullFiles: Map<string, string>;
  repoConventions?: string;
  existingComments: string[];
  totalAdditions: number;
  totalDeletions: number;
}
